name: Build

on:
  push:
    branches:
      - main
      - 2201.[0-9]+.x
    paths-ignore:
      - "*.md"
      - "docs/**"

  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-standard-library/.github/workflows/build-timestamp-master-template.yml@main
    secrets: inherit

  publish_nexus:
    name: Publish to Nexus
    env:
      packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
      packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
      nexusUser: ${{ secrets.NEXUS_USERNAME }}
      nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
    run: |
      ./gradlew clean publishMavenJavaPublicationToWSO2NexusRepository -x test --scan --no-daemon

